version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install

      - save_cache:
          paths:
            - node_modules
          key: frontend_dependencies

      - run:
          name: Install serverless-api dependencies
          command: cd serverless-api && npm install

      - save_cache:
          paths:
            - serverless-api/node_modules
          key: serverless-api_dependencies

      - run:
          name: Deploy application
          command: cd serverless-api && sls deploy --stage prod






workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circleci
