# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: hashtag-lunch-review-backend

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs8.10

  region: eu-north-1

# The `functions` block defines what code to deploy
functions:
  postPlaces:
    handler: src/places.post

    events:
      - http:
          path: places
          method: post

  getPlaces:
    handler: src/places.get

    events:
      - http:
          path: places
          method: get

  postReviews:
    handler: src/reviews.postReviews

    events:
      - http:
          path: reviews
          method: post

  getReviews:
    handler: src/reviews.getReviews

    events:
      - http:
          path: reviews
          method: get

  postUsers:
    handler: src/users.postUser

    events:
      - http:
          path: users
          method: post

  getRatings:
    handler: src/ratings.getRatings

    events:
      - http:
          path: ratings
          method: get

custom:
  dynamodb:
    start:
      seed: true
      migrate: true
    seed:
      domain:
        sources:
          - table: Places
            sources: [./seeds/places.json]
          - table: Reviews
            sources: [./seeds/reviews.json]
  serverless-offline:
    port: 4000

resources:
  - ${file(./serverless_config/dynamo.yml)}
