Resources:
  placeTable:
    Type: AWS::DynamoDB::Table

    Properties:
      TableName: Places

      AttributeDefinitions:
        - AttributeName: placeId
          AttributeType: S
        - AttributeName: placeName
          AttributeType: S

      KeySchema:
        - AttributeName: placeId
          KeyType: HASH

      GlobalSecondaryIndexes:
        - IndexName: placeNameIndex
          KeySchema:
            - AttributeName: placeName
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  reviewsTable:
    Type: AWS::DynamoDB::Table

    Properties:
      TableName: Reviews

      AttributeDefinitions:
        - AttributeName: review_id
          AttributeType: S

      KeySchema:
        - AttributeName: review_id

          KeyType: HASH

      ProvisionedThroughput:
        ReadCapacityUnits: 1

        WriteCapacityUnits: 1

  userTable:
    Type: AWS::DynamoDB::Table

    Properties:
      TableName: User

      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S

      KeySchema:
        - AttributeName: user_id

          KeyType: HASH

      ProvisionedThroughput:
        ReadCapacityUnits: 1

        WriteCapacityUnits: 1
